services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: educluster-api
    ports:
      - "8002:8000"
    depends_on:
      - mlflow
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: educluster-mlflow
    volumes:
      - ./mlruns:/mlflow/mlruns
    ports:
      - "5001:5000"
    restart: unless-stopped